ADD_PRODUCT = "ADD_PRODUCT"
ADD_STOCK = "ADD_STOCK"
SET_STOCK = "SET_STOCK"
GET_STOCK = "GET_STOCK"
REMOVE_PRODUCT = "REMOVE_PRODUCT"
LIST_PRODUCTS = "LIST_PRODUCTS"

PRODUCT_INFO = "PRODUCT_INFO"
SALES_QUERY = "SALES_QUERY"
SALES_PREDICTION = "SALES_PREDICTION"

GENERAL_CHAT = "GENERAL_CHAT"
UNKNOWN = "UNKNOWN"
